### ISSUE TITLE
Losing contigs from VCF info 

### ISSUE THREAD

**Issue by mladvladimir** [chrovis/cljam#23]
Hi, 
There is an issue with **load-meta-info** function in _cljam.vcf.reader_  with VCF files 
which have more than one config; it returns only last one. 
Adding `:contig` key in  

`(if (#{:info :filter :format :alt :sample :pedigree} k)
`

should fixed this.

Regards
Vladimir

**Comment by totakke** [comment]
Thank you for your comment. As you say, `:contig` may have multiple values. I'll fix it.

**Comment by mladvladimir** [comment]
Thanks 👍

**Comment by totakke** [comment]
Fixed in 0.2.0
