### ISSUE TITLE
May need to fix a test for bam-reader with `:chr` argument

### ISSUE THREAD

**Issue by ayamada** [chrovis/cljam#62]
(came from https://github.com/chrovis/cljam/pull/60#discussion_r112161283 )

I add test for bam-reader with `:chr` argument in #60, but I found peculiar results in https://github.com/chrovis/cljam/blob/ff91c66449ddd40b9a48355531550b12fe42c92b/test/cljam/t_bam.clj#L84 .
Possibly I wrong something, but I didn't know this reason.

**Comment by alumi** [comment]
Solved. Thanks!
